### ISSUE TITLE
Provide Homebrew Tap

### ISSUE THREAD

**Issue by cosmo0920** [Elethom/contacts-phonetic#2]
Homebrew provides `Tap` functionality which makes to be able to provide 3rd party Formulae from personal accounts in GitHub.
In more detail, please refer to this article: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md

FYI: I'm a one of the user of Homebrew Tap functionality. I'm willing to help you to create it.

**Comment by Elethom** [comment]
Thank you poi! Working on it.

**Comment by Elethom** [comment]
Created tap repo at [Elethom/homebrew-osxutils](/Elethom/homebrew-osxutils) and added the formula.

ありがとう！ :smile:

**Comment by cosmo0920** [comment]
Oh, it sounds great!
Your Japanese is good.

よかったです！ :smile_cat:

**Comment by Elethom** [comment]
いいえ。私は日本語を話すことはできませんぽい。 Can only manage to put together a few short phrases by what's learned from animes. > <
よろしくぽい！
