### ISSUE TITLE
brew 那边的配方要更新一下？

### ISSUE THREAD

**Issue by zanderzhng** [Elethom/contacts-phonetic#3]
[~] brew install elethom/osxutils/contacts-phonetic
==> Installing contacts-phonetic from elethom/osxutils
==> Downloading https://github.com/Elethom/contacts-phonetic/archive/0.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/contacts-phonetic-0.3.tar.gz
**Error: SHA256 mismatch**
Expected: cf9d04b484fc41837a5f86cade99bb60834a39b08aafa6848d33b6b1f88f1a7d
Actual: 7d08bbfebabc3d1992d6bd66d452228b66ffec570e0250c0f659fd33f836908e
Archive: /Library/Caches/Homebrew/contacts-phonetic-0.3.tar.gz
To retry an incomplete download, remove the file above.

**Comment by Elethom** [comment]
Sorry about the inconvenience. Just updated.
